import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../providers/auth_provider.dart';
import '../../providers/siswa_provider.dart';
import '../../providers/repository_providers.dart';
import '../../../domain/entities/siswa_entity.dart';
import '../../../core/theme/app_theme.dart';

class AddSiswaScreen extends ConsumerStatefulWidget {
  const AddSiswaScreen({super.key});

  @override
  ConsumerState<AddSiswaScreen> createState() => _AddSiswaScreenState();
}

class _AddSiswaScreenState extends ConsumerState<AddSiswaScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nisController = TextEditingController();
  final _namaController = TextEditingController();
  final _alamatController = TextEditingController();
  final _noTelpController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _nisController.dispose();
    _namaController.dispose();
    _alamatController.dispose();
    _noTelpController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (_formKey.currentState!.validate()) {
      final user = ref.read(currentUserProvider);
      
      if (user?.kelasId == null || user?.namaKelas == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Error: Profil Wali Kelas belum memiliki data Kelas. Silakan hubungi Admin.'),
            backgroundColor: Colors.red,
          ),
        );
        return;
      }

      setState(() => _isLoading = true);
      try {
        final repository = ref.read(siswaRepositoryProvider);

        final siswa = SiswaEntity(
          id: '', // Will be generated by backend
          nis: _nisController.text,
          nama: _namaController.text,
          kelasId: user!.kelasId!,
          namaKelas: user.namaKelas!,
          tahunAjaran: '2025/2026', // Can be made dynamic
          semester: 'Ganjil', // Can be made dynamic
          alamat: _alamatController.text,
          noTelp: _noTelpController.text,
        );

        await repository.createSiswa(siswa);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Siswa berhasil ditambahkan'),
              backgroundColor: Colors.green,
            ),
          );
          ref.invalidate(siswaByKelasProvider(user.kelasId!));
          Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('$e'),
              backgroundColor: Colors.red,
            ),
          );
        }
      } finally {
        if (mounted) {
          setState(() => _isLoading = false);
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tambah Siswa'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              TextFormField(
                controller: _nisController,
                decoration: const InputDecoration(
                  labelText: 'NIS',
                  hintText: 'Masukkan NIS Siswa',
                  prefixIcon: Icon(Icons.badge),
                ),
                validator: (value) =>
                    value == null || value.isEmpty ? 'NIS tidak boleh kosong' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _namaController,
                decoration: const InputDecoration(
                  labelText: 'Nama Lengkap',
                  hintText: 'Masukkan Nama Siswa',
                  prefixIcon: Icon(Icons.person),
                ),
                validator: (value) =>
                    value == null || value.isEmpty ? 'Nama tidak boleh kosong' : null,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _alamatController,
                decoration: const InputDecoration(
                  labelText: 'Alamat',
                  hintText: 'Masukkan Alamat Siswa',
                  prefixIcon: Icon(Icons.home),
                ),
                maxLines: 3,
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _noTelpController,
                decoration: const InputDecoration(
                  labelText: 'No. Telp / HP',
                  hintText: 'Contoh: 08123456789',
                  prefixIcon: Icon(Icons.phone),
                ),
                keyboardType: TextInputType.phone,
              ),
              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: _isLoading ? null : _submit,
                style: ElevatedButton.styleFrom(
                  padding: const EdgeInsets.all(16),
                  backgroundColor: AppTheme.primaryColor,
                ),
                child: _isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : const Text(
                        'SIMPAN DATA SISWA',
                        style: TextStyle(fontWeight: FontWeight.bold),
                      ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
